var res = {
	Battle_Scene : "res/BattleScene.json",
	Mypage_Scene :"res/MypageScene.json",
	Menu_Scene :"res/Menu.json",
	Quest_Scene : "res/QuestScene.json",
	Party_Scene : "res/PartyScene.json",
	Synthetic_Scene : "res/SyntheticScene.json",
	Evolution_Scene : "res/EvolutionScene.json",
	Other_Scene : "res/OtherScene.json",
	Title_Scene : "res/TitleScene.json",
	Result_Scene : "res/ResultScene.json",
	Charselect_Scene : "res/CharselectScene.json",
	PlayerBattleAnim : "res/PlayerBattleAnim.json",
	EnemyBattleAnim : "res/EnemyBattleAnim.json",
	
	char_data : "res/charData.json",
	map_data : "res/mapData.json",
	
    jewelry1_png : "res/01.png",
    jewelry2_png : "res/02.png",
    jewelry3_png : "res/03.png",
    jewelry4_png : "res/04.png",
    jewelry5_png : "res/05.png",
    
    princessselect_01_png :"res/char/chara_princessselect_1.png",
    princessselect_02_png :"res/char/chara_princessselect_2.png",
    princessselect_03_png :"res/char/chara_princessselect_3.png",
    princessselect_04_png :"res/char/chara_princessselect_4.png",
    princessselect_05_png :"res/char/chara_princessselect_5.png",
    princessselect_06_png :"res/char/chara_princessselect_6.png",
    princessselect_07_png :"res/char/chara_princessselect_7.png",
    princessselect_08_png :"res/char/chara_princessselect_8.png",
    princessselect_09_png :"res/char/chara_princessselect_9.png",
    princessselect_10_png :"res/char/chara_princessselect_10.png",
    princessselect_11_png :"res/char/chara_princessselect_11.png",
    princessselect_12_png :"res/char/chara_princessselect_12.png",
    
    player_01_png : "res/char/chara_player_1.png",
    player_02_png : "res/char/chara_player_2.png",
    player_03_png : "res/char/chara_player_3.png",
    player_04_png : "res/char/chara_player_4.png",
    player_05_png : "res/char/chara_player_5.png",
    player_06_png : "res/char/chara_player_6.png",
    player_07_png : "res/char/chara_player_7.png",
    player_08_png : "res/char/chara_player_8.png",
    player_09_png : "res/char/chara_player_9.png",
    player_10_png : "res/char/chara_player_10.png",
    player_11_png : "res/char/chara_player_11.png",
    player_12_png : "res/char/chara_player_12.png",
    
    charIcon_00_png : "res/char/icon_chara_b_1.png",
    charIcon_01_png : "res/char/icon_chara_b_1.png",
    charIcon_02_png : "res/char/icon_chara_b_2.png",
    charIcon_03_png : "res/char/icon_chara_b_3.png",
    charIcon_04_png : "res/char/icon_chara_b_4.png",
    charIcon_05_png : "res/char/icon_chara_b_5.png",
    charIcon_06_png : "res/char/icon_chara_b_6.png",
    charIcon_07_png : "res/char/icon_chara_b_7.png",
    charIcon_08_png : "res/char/icon_chara_b_8.png",
    charIcon_09_png : "res/char/icon_chara_b_9.png",
    charIcon_10_png : "res/char/icon_chara_b_10.png",
    charIcon_11_png : "res/char/icon_chara_b_11.png",
    charIcon_12_png : "res/char/icon_chara_b_12.png",
    
    charBattleIcon_00_png : "res/char/icon_chara_a_1.png",
    charBattleIcon_01_png : "res/char/icon_chara_a_1.png",
    charBattleIcon_02_png : "res/char/icon_chara_a_2.png",
    charBattleIcon_03_png : "res/char/icon_chara_a_3.png",
    charBattleIcon_04_png : "res/char/icon_chara_a_4.png",
    charBattleIcon_05_png : "res/char/icon_chara_a_5.png",
    charBattleIcon_06_png : "res/char/icon_chara_a_6.png",
    charBattleIcon_07_png : "res/char/icon_chara_a_7.png",
    charBattleIcon_08_png : "res/char/icon_chara_a_8.png",
    charBattleIcon_09_png : "res/char/icon_chara_a_9.png",
    charBattleIcon_10_png : "res/char/icon_chara_a_10.png",
    charBattleIcon_11_png : "res/char/icon_chara_a_11.png",
    charBattleIcon_12_png : "res/char/icon_chara_a_12.png",
    
    enemy_01_png : "res/char/chara_enemy_1.png",
    enemy_02_png : "res/char/chara_enemy_2.png",
    enemy_03_png : "res/char/chara_enemy_3.png",
    enemy_04_png : "res/char/chara_enemy_4.png",
    enemy_05_png : "res/char/chara_enemy_5.png",
    enemy_06_png : "res/char/chara_enemy_6.png",
    enemy_07_png : "res/char/chara_enemy_7.png",
    enemy_08_png : "res/char/chara_enemy_8.png",
    enemy_09_png : "res/char/chara_enemy_9.png",
    
    enemyIcon_01_png : "res/char/enemy_1.png",
    enemyIcon_02_png : "res/char/enemy_2.png",
    enemyIcon_03_png : "res/char/enemy_3.png",
    enemyIcon_04_png : "res/char/enemy_4.png",
    enemyIcon_05_png : "res/char/enemy_5.png",
    enemyIcon_06_png : "res/char/enemy_6.png",
    enemyIcon_07_png : "res/char/enemy_7.png",
    enemyIcon_08_png : "res/char/enemy_8.png",
    enemyIcon_09_png : "res/char/enemy_9.png",
    
    Fire_texture1_plist : "res/effect/Fire_texture1.plist",
    Fire_texture2_plist : "res/effect/Fire_texture2.plist",
    Fire_texture3_plist : "res/effect/Fire_texture3.plist",
    Fire_texture4_plist : "res/effect/Fire_texture4.plist",
    Water_texture1_plist : "res/effect/Water_texture1.plist",
    Water_texture2_plist : "res/effect/Water_texture2.plist",
    Water_texture3_plist : "res/effect/Water_texture3.plist",
    Water_texture4_plist : "res/effect/Water_texture4.plist",
    Wood_texture1_plist : "res/effect/Wood_texture1.plist",
    Wood_texture2_plist : "res/effect/Wood_texture2.plist",
    Wood_texture3_plist : "res/effect/Wood_texture3.plist",
    Wood_texture4_plist : "res/effect/Wood_texture4.plist",
    Heal_texture1_plist : "res/effect/Heal_texture1.plist",
    Slip_texture1_plist : "res/effect/Slip_texture1.plist",
    
    ALL_BGM : "res/all_bgm.mp3",
    BATTLE_BGM : "res/battle.mp3",
    VICTORY_JINGLE : "res/victory.mp3",
    LOSE_JINGLE : "res/lose.mp3",
    LEVELUP_JINGLE : "res/levelup.mp3",
    HIT_SE : "res/hit.mp3",
    SKILL1_SE : "res/skill1.mp3",
    SKILL2_SE : "res/skill2.mp3",
    SKILL3_SE : "res/skill3.mp3",
    SKILL4_SE : "res/skill4.mp3",
    SKILL5_SE : "res/skill5.mp3",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}