# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PuzzleRPG-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuzzleRPG-desktop

end

target 'PuzzleRPG-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuzzleRPG-mobile

end
