# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'PuzzleRPG-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuzzleRPG-mobile
  pod 'Firebase'
  pod 'Firebase/AdMob'

end
